### ISSUE TITLE
Surely should all registers be signed?

### ISSUE THREAD

**Issue by lightspot21** [chip16/chip16#24]
Unless I'm seriously wrong somewhere, I think it should be clarified that when talking about signed registers, only the 16 general registers shall be signed. Does it make sense to talk about a signed program counter, or a stack pointer?

**Comment by prospero78** [comment]
If we talk about a holistic approach, then the necessary condition is the implementation of all processor registers with support for signed integer values. Indexing the register of a software counter with a sign is a good idea. Since when writing programs, you have to save the value of the register of the program counter on the stack, or for example - dynamically calculate the necessary transition points during the program. If the program counter does not have a sign, these will be problems that could have been avoided from the very beginning.

**Comment by lightspot21** [comment]
To be honest, I didn't expect to get a response that fast :astonished: 

I see what you mean, but why then do the reference emulators use unsigned variables to store signed data? (I'm asking because I'm making my own emulator and if I use signed data type for the registers then they can't be used for indexing all memory without overflowing and causing a crash, unless I cast them to unsigned, something that I'd like to avoid)

**Comment by prospero78** [comment]
I think that you do not fully understand the idea of processor registers for use with a sign. If you are modeling a memory block, then the addressing of this memory block should begin with -intMax and end with + intMax. I think that translation into an unsigned integer of the memory address is done because golang (for example) cannot work with negative indices. python can do slices with indexes, but for obvious reasons, doing similar implementations of processor emulators in python is a pretty weak solution.

**Comment by metteo** [comment]
@prospero78 then why reference implementation uses `uint16_t` for both pc and sp: [cpu.h:106](https://github.com/tykel/mash16/blob/jit/src/core/cpu.h#L106)?

**Comment by prospero78** [comment]
@metteo, I have two options to explain this solution:
1) in C, it is impossible to use negative indices for addressing memory (it is obvious that as part of RAM in the processor model, it is not an array but a part of memory with direct mapping in memory that is used, that is, the author is set up for a backward legacy of x86 architecture, which means an attempt to adapt the logic to the maximum speed of the emulator).
2) the author uses an array for RAM, but made the wrong choice in the architecture of the processor emulator. Then, of course, this is a mistake and a step back. This step will inevitably lead to unnecessary complication of the processor model, there will be errors in the code, unnecessary conversions from an unsigned integer to a signed integer and vice versa.

**Comment by tykel** [comment]
@lightspot21 You are correct in saying only registers r0..r15 are signed.
A signed program counter (PC) or stack pointer (SP) do not make sense as they are pointers to memory locations, which as @prospero78 pointed out is non-sensical.

I will amend the documentation and wiki to clarify this.
